name: annealing_experiments
channels:
  - defaults
  - twesterhout
dependencies:
  - python=3.9
  - pip
  - ising-glass-annealer =0.4.1.2
  - lattice-symmetries =0.8.3
  - cffi
  - h5py
  - pyyaml
  - networkx
  - numpy
  - scipy
  - loguru
  - numba
  # Tools for development
  - black
  - isort
  - mypy
