name: annealing_gpu
channels:
  - pytorch
  - twesterhout
  - conda-forge
dependencies:
  - python
  - pip
  # - torchvision
  - pip:
    - black
      # - grip
    - neovim
  # - cpuonly
  - cudatoolkit=10.2
  - pytorch=1.9.1=*cuda*
  - unpack-bits=*=*cuda*
  - ising-glass-annealer>=0.2.0.1
  - lattice-symmetries
  - gcc_linux-64
  - h5py
  - pyyaml
  - numpy
  - scipy
  - loguru
  - tensorboard
  #  - matplotlib
